
services:
  app_baralho_magico:
    build: 
      dockerfile: ./dockerfile
      context: .
    image: renatoelho/app-baralho-magico:0.0.1
    hostname: app_baralho_magico
    container_name: app_baralho_magico
    environment:
      - PYTHONPATH=/home/streamlit/python/streamlit/
      - TZ=America/Sao_Paulo
      - TERM=xterm-256color
    ports:
      - "8100:8100"
    deploy:
      resources:
        limits:
          cpus: "0.95"
          memory: 2G
    restart: always
    healthcheck:
      test: curl -f http://app_baralho_magico:8100 || exit 1
      interval: 60s
      timeout: 15s
      retries: 5
    networks:
      - rede

networks:
  rede:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.2.1.0/30